#!/system/bin/sh

# Remove old tweaks
if [ -e "/system/test.prop(2)" ] 
then
    rm -f "/system/test.prop(2)" else
if [ -e "/system/tweaks.prop" ] 
then
    rm -f "/system/tweaks.prop"
fi
if [ -e "/system/etc/sysctl" ]
then
    rm -f "/system/etc/sysctl" else
fi

rm $0
