#!/system/bin/sh
#Lightning Zap universal tweaks. Since I have added most of the values for the LZ scripts, I decided to combine the remaining scripts.

mount -o remount rw /system;

# 0remount
#Partition mounts by Dsexton702
mount -o remount,noatime,nobh,nodiratime,nodelalloc,noauto_da_alloc,barrier=0 /system /system;
mount -o remount,noatime,nobh,nodiratime,nodelalloc,noauto_da_alloc,barrier=0 /cache /cache;
mount -o remount,noatime,nodiratime,delalloc,noauto_da_alloc,barrier=0 /data /data;

#Sick Tweaks
rm -f /cache/*.apk;
rm -f /cache/*.tmp;
rm -f /data/dalvik-cache/*.apk;
rm -f /data/dalvik-cache/*.tmp;
