#!/system/bin/sh
#Raises read ahead to 4096. Enhances memory and RAM settings. Enhances network speed. Optimizes kernel features.
#Added some values from Team Kang

mount -o remount rw /system

# Set io scheduler tweaks for mmc
	echo "cfq" > /sys/block/mmcblk0/queue/scheduler
	echo "0" > /sys/block/mmcblk0/queue/rotational
	echo "4096" > /sys/block/mmcblk0/queue/nr_requests
	echo ${READ_AHEAD_KB} > /sys/block/mmcblk0/queue/read_ahead_kb

#Sick Tweaks
rm -f /cache/*.apk
rm -f /cache/*.tmp
rm -f /data/dalvik-cache/*.apk
rm -f /data/dalvik-cache/*.tmp

# =========
# TWEAKS: raising read_ahead_kb cache-value for sd card to 4096 [not needed with above tweak but just in case it doesn't get applied]
# =========
# improved approach of the readahead-tweak:

READ_AHEAD_KB="4096"

if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:0/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

# =============
# Kernel tweaks
# =============
echo "now enabling sched_child_runs_first"
echo "1" > /proc/sys/kernel/sched_child_runs_first
cat /proc/sys/kernel/sched_child_runs_first
echo "done"
echo ""
