#!/system/bin/sh
#Removes 1 time needed scripts (for cleanup purposes).
#Finalizes tweaks

mount -o remount rw /system
mount -o remount rw /

echo "finishing up";
sync;
setprop cm.filesystem.ready 1;

echo "remounting"
mount -o remount rw /;
echo "Done";
 
