#!/system/bin/sh
#Battery Tweaks
#To select a tweak, remove the "#" before the setting
#Optimal values for up_threshold is 45-85. Higher number=higher battery/lower performance. Lower number=higher performance/lower battery life

mount -o remount rw /system

#=========
#OnDemand
#=========
AWAKE_GOVERNOR="ondemand"
#SLEEP_GOVERNOR="ondemand"
	#echo "45" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold;
#===================================
#0=off  1=on
#===================================	
	#echo "0" > /sys/devices/system/cpu/cpufreq/ondemand/powersave_bias;
	#echo "0" > /sys/devices/system/cpu/cpufreq/ondemand/ignore_nice_load
	echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy;
#===================================
#Do not change smapling_rate values
#===================================
	echo "150000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate;

echo "Setting Awake Governor";
echo "Setting up_threshold";
echo "Setting powersave_bias";
echo "Setting io_is_busy";
sleep 1
echo "Done"
